/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

declare const self: ServiceWorkerGlobalScope

// Take control of all pages under this service worker's scope immediately
self.skipWaiting()
clientsClaim()

// Precache all of the assets generated by your build process
precacheAndRoute(self.__WB_MANIFEST)
